# Generated by Django 5.2.4 on 2025-07-24 10:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZaakType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "identificatie",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt.",
                        max_length=50,
                        verbose_name="identificatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaaktype",
                "verbose_name_plural": "Zaaktypen",
            },
        ),
    ]
