# Generated by Django 5.2.4 on 2025-07-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="omschrijving",
            field=models.CharField(
                blank=True,
                help_text="Een korte omschrijving van de zaak.",
                max_length=80,
            ),
        ),
    ]
