# Generated by Django 5.2.4 on 2025-07-21 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0002_zaak_omschrijving"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Unieke resource identifier (UUID4)"
            ),
        ),
    ]
