# Generated by Django 5.2.4 on 2025-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zaken", "0003_zaak_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="archiefnominatie",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "blijvend_bewaren",
                        "Het zaakdossier moet bewaard blijven en op de Archiefactiedatum overgedragen worden naar een archiefbewaarplaats.",
                    ),
                    (
                        "vernietigen",
                        "Het zaakdossier moet op of na de Archiefactiedatum vernietigd worden.",
                    ),
                ],
                db_index=True,
                max_length=40,
                null=True,
                verbose_name="archiefnominatie",
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="archiefstatus",
            field=models.CharField(
                db_index=True, max_length=40, null=True, verbose_name="archiefstatus"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="betalingsindicatie",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "nvt",
                        "Er is geen sprake van te betalen, met de zaak gemoeide, kosten.",
                    ),
                    (
                        "nog_niet",
                        "De met de zaak gemoeide kosten zijn (nog) niet betaald.",
                    ),
                    (
                        "gedeeltelijk",
                        "De met de zaak gemoeide kosten zijn gedeeltelijk betaald.",
                    ),
                    ("geheel", "De met de zaak gemoeide kosten zijn geheel betaald."),
                ],
                max_length=20,
                verbose_name="betalingsindicatie",
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="communicatiekanaal_naam",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="communicatiekanaal naam"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="opschorting_eerdere_opschorting",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="eerdere opschorting"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="opschorting_indicatie",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="indicatie opschorting"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="opschorting_reden",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="reden opschorting"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="processobject_datumkenmerk",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="datumkenmerk"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="processobject_identificatie",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="identificatie"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="processobject_objecttype",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="objecttype"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="processobject_registratie",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="registratie"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="processobjectaard",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="procesobjectaard"
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="toelichting",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="zaak",
            name="verlenging_reden",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="reden verlenging"
            ),
        ),
    ]
