# Generated by Django 5.2.4 on 2025-07-23 07:42

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zaken", "0004_zaak_archiefnominatie_zaak_archiefstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="archiefactiedatum",
            field=models.DateField(
                blank=True, db_index=True, default=datetime.date.today, null=True
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="zaak",
            name="einddatum",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name="zaak",
            name="einddatum_gepland",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name="zaak",
            name="laatste_betaaldatum",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="publicatiedatum",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name="zaak",
            name="registratiedatum",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="zaak",
            name="startdatum",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="zaak",
            name="startdatum_bewaartermijn",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name="zaak",
            name="uiterlijke_einddatum_afdoening",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
