# Generated by Django 5.2.4 on 2025-07-23 09:46

from django.db import migrations

import vng_api_common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("zaken", "0005_zaak_archiefactiedatum_zaak_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="opdrachtgevende_organisatie",
            field=vng_api_common.fields.RSINField(default="123456782", max_length=9),
        ),
        migrations.AddField(
            model_name="zaak",
            name="verantwoordelijke_organisatie",
            field=vng_api_common.fields.RSINField(default="123456782", max_length=9),
        ),
    ]
