# Generated by Django 5.2.4 on 2025-07-23 10:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zaken", "0006_zaak_opdrachtgevende_organisatie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="zaakgeometrie",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
