# Generated by Django 5.2.4 on 2025-07-23 10:37

import openzaak_new.components.zaken.models
import vng_api_common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaken", "0007_zaak_zaakgeometrie"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="communicatiekanaal",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="zaak",
            name="selectielijstklasse",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="zaak",
            name="verlenging_duur",
            field=openzaak_new.components.zaken.models.DurationField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="vertrouwelijkheidaanduiding",
            field=vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                choices=[
                    ("openbaar", "Openbaar"),
                    ("beperkt_openbaar", "Beperkt openbaar"),
                    ("intern", "Intern"),
                    ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                    ("vertrouwelijk", "Vertrouwelijk"),
                    ("confidentieel", "Confidentieel"),
                    ("geheim", "Geheim"),
                    ("zeer_geheim", "Zeer geheim"),
                ],
                default="openbaar",
                max_length=20,
            ),
        ),
    ]
