# Generated by Django 5.2.4 on 2025-07-23 10:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zaken", "0008_zaak_communicatiekanaal_zaak_selectielijstklasse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="producten_of_diensten",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=1000),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
