# Generated by Django 5.2.4 on 2025-07-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zaken", "0009_zaak_producten_of_diensten"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="hoofdzaak",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"hoofdzaak__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deelzaken",
                to="zaken.zaak",
                verbose_name="is deelzaak van",
            ),
        ),
    ]
