# Generated by Django 5.2.4 on 2025-07-24 10:32

import django.db.models.deletion
from django.db import migrations, models

import zgw_consumers.models.fields

import openzaak_new.components.zaken.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogi", "0001_initial"),
        ("zaken", "0010_zaak_hoofdzaak"),
        ("zgw_consumers", "0026_remove_service_oas_remove_service_oas_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="_zaaktype",
            field=models.ForeignKey(
                blank=True,
                help_text="URL-referentie naar het ZAAKTYPE (in de Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogi.zaaktype",
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="_zaaktype_base_url",
            field=openzaak_new.components.zaken.models.ServiceFkField(
                blank=True,
                help_text="Basis deel van URL-referentie naar het extern ZAAKTYPE (in een andere Catalogi API).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="_zaaktype_relative_url",
            field=openzaak_new.components.zaken.models.RelativeURLField(
                blank=True,
                help_text="Relatief deel van URL-referentie naar het extern ZAAKTYPE (in een andere Catalogi API).",
                max_length=1000,
                null=True,
                verbose_name="zaaktype relative url",
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="_zaaktype_url",
            field=zgw_consumers.models.fields.ServiceUrlField(
                base_field="_zaaktype_base_url",
                blank=True,
                null=True,
                relative_field="_zaaktype_relative_url",
            ),
        ),
        migrations.AddField(
            model_name="zaak",
            name="zaaktype",
            field=openzaak_new.components.zaken.models.FkOrServiceUrlField(
                blank=False, fk_field="_zaaktype", null=True, url_field="_zaaktype_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="zaak",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("_zaaktype_base_url__isnull", True),
                        models.Q(
                            ("_zaaktype_relative_url__isnull", True),
                            ("_zaaktype_relative_url", ""),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("_zaaktype_base_url__isnull", True), _negated=True),
                        models.Q(
                            ("_zaaktype_relative_url__isnull", True),
                            ("_zaaktype_relative_url", ""),
                            _connector="OR",
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="zaken_zaak__zaaktype_base_url_and__zaaktype_relative_url_filled",
            ),
        ),
    ]
