# Generated by Django 5.2.4 on 2025-07-25 08:14

from django.db import migrations, models

import vng_api_common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("zaken", "0011_zaak__zaaktype_zaak__zaaktype_base_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="bronorganisatie",
            field=vng_api_common.fields.RSINField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="zaak",
            name="identificatie",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
    ]
